version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8   
    working_directory: /go/src/github.com/monosolutions/mono-go-image-cli
    steps:
      - checkout     
      - run:
          name: Release Tool
          command: go get github.com/goreleaser/goreleaser     
      - run:
          name: Build          
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                VERSION="0.0.${CIRCLE_BUILD_NUM}"                         
                git config --global user.email "mlu@monosolutions.com"
                git config --global user.name "mono-deployment"
                git tag -a $VERSION -m "v${VERSION}"            
                goreleaser                   
            fi
       

                 
